name: voice_translator
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0
  translator: ^1.0.3+1
  flutter_tts: ^4.2.2
  loading_indicator: ^3.1.1
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1
  


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ApplicationLogo.png"   

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3  


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/launchScreenIllustrators.png

  fonts:
    - family: Viga
      fonts:
        - asset : assets/fonts/Viga-Regular.ttf

